application:
  name: bumacat
datasource:
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${DB_URL}
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
server:
  port: ${SERVER_PORT}